# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c0ad0035b7cb3a2aebaa6d50e38e9beb05939d4f917b91e8ea19239c4e574cfa0962650b68fb4fe254cac654e68306e84a5abab392175fa7c65301f39673fe

test:
  secret_key_base: 2284e14018364ab417f64fa71578804caea2690af66fba380ff996c9fef7a1e03a43918bf04a6dfb5c77bb09789efd4c5412fac2dcdd8eb0f7e952c1b3d167f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
